### PR TITLE
Feature/replace borders for icons in the navigation and close button

### PR DESCRIPTION
**Pull request by xbindt**
replace borders for icons in the navigation and close button and some code cleanup

### CODE REVIEW

**Review by field2 — COMMENTED** [review]
Thanks for the cleanup-it definitely needed that. 
The plugin already has left/right/close icons, so this pr doesn't add them. It'd be more accurate to say use dashicons for left/right/close icons. Also, why is it an improvement to use dashicons instead?

**Comment by xbindt** [comment]
> Thanks for the cleanup-it definitely needed that. The plugin already has left/right/close icons, so this pr doesn't add them. It'd be more accurate to say use dashicons for left/right/close icons. Also, why is it an improvement to use dashicons instead?

I changed it because the current icon's implementation did not look/scale ok on/to mobile.. i could have  changed the width from the border impl. but i thought the icons looke better...

**Comment by field2** [comment]
OK, that makes sense. Thanks!

**Review by field2 — COMMENTED** [review]
Looks good

**Pull request merged**
